# Métrica v.3 {.unnumbered .unlisted}

La metodología MÉTRICA Versión 3 ofrece a las Organizaciones un instrumento útil para la sistematización de las actividades que dan soporte al ciclo de vida del software.

**Metodología de Planificación, Desarrollo y Mantenimiento de sistemas de información**

Se presentan en esta página los documentos que componen la metodología MÉTRICA VERSIÓN 3. Iniciativa promovida por el Consejo Superior de Informática –publicada en 2001 en la web del CSI–. 

MÉTRICA versión 3 puede ser utilizada libremente y en cualquier explotación de la obra se hará constar la autoría original.

\
Para cualquier sugerencia o información sobre la metodología Métrica v3, contactar con: <metrica@correo.gob.es>

Para cuestiones relacionadas con el repositorio de ficheros fuente o sus versiones web y PDF derivadas, abrir un issue en GitHub.

\
| Recurso | URL |
| - | - |
| Versión web | [pmgallardo.github.io/metrica-v3](https://pmgallardo.github.io/metrica-v3) |
| Repositorio de ficheros fuente | [github.com/pmgallardo/metrica-v3](https://github.com/pmgallardo/metrica-v3) |
| Repositorio de documentación original | [administracionelectronica.gob.es/pae_Home/pae_Documentacion/pae_Metodolog/pae_Metrica_v3.html](https://administracionelectronica.gob.es/pae_Home/pae_Documentacion/pae_Metodolog/pae_Metrica_v3.html?idioma=es) |
