# Participantes

MÉTRICA Versión 3 ha sido concebida para abarcar el desarrollo completo de Sistemas de Información sea cual sea su complejidad y magnitud, por lo cual su estructura y los perfiles de los participantes que intervienen deberán adaptarse y dimensionarse en cada momento de acuerdo a las características particulares de cada proyecto.

Para poder exponer una estructura de los participantes que se han identificado a lo largo de los procesos de la Metodología MÉTRICA Versión 3, se ha optado por establecer una serie de perfiles en los que se encuadran la totalidad de los participantes. Estos perfiles coinciden con los elegidos para el Plan de Formación y la herramienta de autoformación en MÉTRICA Versión 3, obteniéndose de este modo una visión homogénea de la metodología. Se ha considerado que esta es una clasificación en la que se pueden resumir las funciones y responsabilidades de los participantes, ya que en la mayoría de los casos intervienen en los mismos procesos principales definidos en MÉTRICA Versión 3 y el conocimiento que han de tener sobre la metodología coincide.

Los perfiles establecidos son:

    Directivo
    Jefe de Proyecto
    Consultor
    Analista
    Programador

Para cada uno de estos perfiles se analizan una serie de características importantes a la hora de delimitar su participación en el proyecto:

    Correspondencia con Participantes de MÉTRICA Versión 3.
    Responsabilidades o funciones a desempeñar en cada uno de los procesos.
    Perfil o características propias de cada uno de los participantes.

## Directivo

Dentro de esta categoría se agrupan los siguientes participantes:

- Comité de Dirección
- Comité de Seguimiento
- Directores de usuarios
- Usuarios expertos

Intervienen en todos los procesos principales de MÉTRICA Versión 3, siendo sus principales responsabilidades y funciones similares, si bien dependiendo del proceso estas pueden experimentar pequeñas variaciones.

El perfil requerido para este grupo de participantes incluye a personas con un nivel alto en la dirección de la organización, conocimiento de los objetivos estratégicos y de negocio que se persiguen y autoridad para validar y aprobar cada uno de los procesos realizados durante el desarrollo del Sistema de Información. Además deben tener un conocimiento del entorno y de la organización suficiente para proporcionar, a lo largo de todo el proyecto, unos requisitos del Sistema adecuados, completos y suficientemente importantes como para considerarse en el catálogo definitivo de requisitos.

Es responsabilidad del Comité de Dirección proveer los recursos necesarios para el cumplimiento de los objetivos propuestos, revisar y aprobar formalmente cada uno de los procesos. Este Comité supone la implicación directa de la alta dirección de la organización en el proyecto, si bien su constitución variará en función de las características del mismo.

Los Directores de las áreas organizativas y de usuarios afectadas por el proyecto aportan información sobre las necesidades planteadas y validan los resultados con el fin de garantizar la identificación, comprensión e incorporación de todos los requisitos con las prioridades adecuadas. Esta misma función la desempeñan con mayor nivel de detalle los usuarios expertos de nivel directivo.

El seguimiento y control del desarrollo del proyecto es responsabilidad del Comité de Seguimiento, que se ocupará de resolver cualquier contingencia que pueda presentarse durante la ejecución del mismo y asegurará la disponibilidad de recursos humanos con los perfiles adecuados y su participación en las actividades donde es necesaria su colaboración.

## Jefe de Proyecto

Los participantes que se engloban dentro de este perfil son los que se detallan a continuación:

- Jefe de Proyecto
- Responsable de Implantación
- Responsable de Mantenimiento
- Responsable de Operación
- Responsable de Sistemas
- Responsable de Seguridad
- Responsable de Calidad

Todos ellos ejercen labores de coordinación y dirección de equipos humanos especializados en la realización de actividades propias de un proceso o interfaz de MÉTRICA Versión 3. La figura principal es el Jefe de Proyecto, el cual recibe el apoyo de los distintos responsables durante la realización de procesos o determinadas actividades a lo largo del proyecto.

El Jefe de Proyecto realiza la estimación del esfuerzo necesario para llevar a cabo el proyecto, selecciona la estrategia de desarrollo, determina la estructura del mismo seleccionando los procesos principales de MÉTRICA Versión 3 que lo integran, fija el calendario de hitos y entregas y establece la planificación del proyecto. Es el encargado de dirigir el proyecto, realizando las labores de seguimiento y control del mismo, revisión y evaluación de resultados y coordinación del equipo de proyecto. Se ocupa también de la gestión y resolución de incidencias que puedan surgir durante el desarrollo del proyecto así como de la actualización de la planificación inicial. Entre sus funciones se encuentran la elaboración de los informes de seguimiento y el archivo de la documentación de gestión del proyecto una vez que este ha finalizado.

Los Responsables de Implantación, Operación, Sistemas y Mantenimiento intervienen en procesos principales de MÉTRICA Versión 3, ofreciendo apoyo al Jefe de Proyecto durante la realización de sus actividades. Poseen mayor conocimiento de los aspectos organizativos y de procedimiento habituales en la organización en sus áreas de responsabilidad concretas, facilitando el desarrollo de los procesos que afectan a esas áreas. Aseguran la disponibilidad de los recursos necesarios y la participación activa del equipo humano que coordinan.

Los Responsables de Seguridad y Calidad aportan información relativa a las normas y procedimientos habituales en la organización, completándolos en su caso de acuerdo con los requerimientos particulares del sistema en colaboración con el Jefe de Proyecto. Ofrecen asesoramiento sobre todos los aspectos de seguridad y calidad relativos tanto al producto como al proceso seguido para su obtención, analizando los riesgos y determinando las medidas de control oportunas. Coordinan a los integrantes del Equipo de Seguridad y el Grupo de Aseguramiento de la Calidad.

## Consultor

En este perfil se incluyen los siguientes participantes:

- Consultor
- Consultor Informático
- Consultor de las Tecnologías de la Información
- Consultor de Sistemas de Información
- Especialista en Comunicaciones
- Técnico de Sistemas
- Técnicos de Comunicaciones

La principal función de los Consultores es asesorar en las cuestiones sobre las que tienen un conocimiento especializado. Se diferencia así entre Consultor, que asesora en los aspectos relativos al negocio y Consultor Informático, con un nivel de especialización mayor en los aspectos relacionados con la informática, su aplicación e integración en la organización.

En el ámbito de la Consultoría Informática se distingue entre Tecnologías de la Información y Sistemas de Información. El Consultor en Tecnologías de la Información aporta un mayor conocimiento de las últimas tecnologías, colabora en la evaluación de distintas alternativas tecnológicas y participa en la validación y selección de la solución más adecuada para el sistema a desarrollar, mientras que el Consultor de Sistemas de Información ofrece una opinión experta, pericia o conocimientos relativos a los requisitos del negocio, técnicos y de usuario que han de tenerse en cuenta en el desarrollo de un sistema de información.

Los Técnicos y Especialistas en Sistemas y Comunicaciones cuentan con una visión más precisa de la tecnología existente en la actualidad en la organización o que se valora incorporar, en cuanto a sus requerimientos técnicos, entorno e infraestructura que precisan, implantación, integración con otros sistemas existentes, configuración y pruebas. Aportan su conocimiento y experiencia práctica a la hora de valorar alternativas tecnológicas para el sistema de información, participando activamente durante su implantación y puesta en producción.

## Analista

En el perfil de Analista se agrupan los siguientes participantes de MÉTRICA Versión 3:

- Analista
- Administrador de Bases de Datos
- Equipo de Arquitectura
- Equipo de Formación
- Equipo de Implantación
- Equipo de Operación
- Equipo de Seguridad
- Equipo de Soporte Técnico
- Equipo de Proyecto
- Grupo de Aseguramiento de la Calidad

La responsabilidad de los Analistas es elaborar un catálogo detallado de requisitos que permita describir con precisión el sistema de información, para lo cual mantendrán entrevistas y sesiones de trabajo con los responsables de la organziación y usuarios, actuando de el interlocutor entre éstos y el equipo de proyecto en lo que a requerimientos se refiere. Estos requisitos permiten a los analistas eleborar los distintos modelos que sirven de base para el diseño, obteniendo los modelos de datos y de procesos en el caso del análisis estructurado y los modelos de clases e interacción de objetos en análisis orientado a objeto. Asi mismo realizan la especificación de las interfaces entre el sistema y el usuario.

El Administrador de Bases de Datos participa en la obtención del diseño físico de datos, definiendo la estructura física de datos que utilizará el sistema a partir del modelo lógico de datos normalizado o del modelo de clases, teniendo presentes las características específicas del sistema de gestión de base de datos concreto a utilizar, los requisitos establecidos para el sistema de información, y las particularidades del entorno tecnológico, se consiga una mayor eficiencia en el tratamiento de los datos. Si se va a realizar una migración de datos colabora con el equipo de proyecto estimando los volúmenes de las estructuras de datos implicadas, definiendo los mecanismos de migración y carga inicial de datos y participando activamente en su realización. Una vez que el sistema está en producción se ocupa de la gestión y operativa asociada a las bases de datos y al software en el que están implementadas.

Los integrantes del Equipo de Proyecto participan a lo largo de todo el proceso de desarrollo y mantenimiento del sistema de información, si bien su composición puede ir variando en función de las características del proyecto y del proceso que se esté realizando, diferenciando así los Equipos de Implantación, Operación, Mantenimiento, Arquitectura, Soporte Técnico y Seguridad, coordinados por un Resposable de Equipo, cuyas funciones y perfiles están más especializadas para la realización de un proceso o interfaz concreto.

El Equipo de Formación es el encargado de preparar e impartir la formación al equipo responsable de la implantación y operación del sistema, para lo cual se encarga de elaborar un plan de formación que incluye los cursos de formación y sus contenidos, así como los recursos humanos y de infraestructura para llevarlo a cabo. Igualmente define el contenido de la formación que deberá recibir el usuario final del sistema, realizando su seguimiento.

El Grupo de Aseguramiento de la Calidad, dirigido por el Responsable de Calidad, desarrolla el plan de aseguramiento de calidad específico para el proyecto, reflejando en dicho plan entre otros aspectos las actividades de calidad a realizar (normales o extraordinarias). Participa en la revisión de los productos seleccionados para determinar si son conformes o no a los procedimientos, normas o criterios especificados, comprobando que se han llevado a cabo las medidas preventivas o correctoras necesarias. Este grupo es completamente independiente del equipo de proyecto.

## Programador

Dado que la participación y funciones de los programadores son concretas y limitadas a los procesos de Construcción y Mantenimiento de Sistemas de Información, el perfil de Programador hace referencia únicamente al participante Programador descrito en MÉTRICA Versión 3.

La función del programador, miembro del equipo de proyecto, es construir el código que dará lugar al producto resultante en base al diseño técnico realizado por el analista o analista programador, generando también el código asociado a los procedimientos de migración y carga inicial de datos. Igualmente se encarga de la realización de las pruebas unitarias y participa en las pruebas de conjunto de la aplicación.

